(function () {
  "use strict";
  const $ = (id) => document.getElementById(id);
  const loginCard = $("login-card"), adminCard = $("admin-card"), loginForm = $("login-form"), password = $("admin-password"), loginNotice = $("login-notice"), form = $("option-form"), list = $("option-list"), notice = $("option-notice"), save = $("save-options"), baseList = $("base-icon-list"), newIcon = $("option-icon");
  const catalog = window.GAIA_ICON_CATALOG || { sparkles: "Nuevo" };
  const defaults = { password: "key", access: "access", failure: "alert", configuration: "settings", equipment: "laptop", system: "system", consultation: "consultation" };
  const base = [["password", "Olvidé mi contraseña"], ["access", "Necesito acceso"], ["failure", "Reportar una falla"], ["configuration", "Configuración"], ["equipment", "Equipo o dispositivo"], ["system", "Sistema o plataforma"], ["consultation", "Hacer consulta"]];
  let options = [], icons = {}, kiosk = { width: 1024, height: 768 };
  const note = (target, text, error) => { target.textContent = text; target.className = error ? "notice error" : "notice"; };
  const normalizeCedula = (value) => typeof value === "string" && /^[0-9\s\-\u2010-\u2015]*$/u.test(value) && /^[0-9]{11}$/.test(value.replace(/[\s\-\u2010-\u2015]/gu, "")) ? value.replace(/[\s\-\u2010-\u2015]/gu, "") : null;
  function icon(name) { const box = document.createElement("span"); box.className = "icon-preview"; if (window.gaiaIconElement) box.appendChild(window.gaiaIconElement(name)); return box; }
  function select(value) { const el = document.createElement("select"); Object.entries(catalog).forEach(([id, label]) => { const item = document.createElement("option"); item.value = id; item.textContent = label; item.selected = id === value; el.appendChild(item); }); return el; }
  function addChangeIcon(row, selected, change) { const picker = select(selected); picker.addEventListener("change", () => { change(picker.value); const old = row.querySelector(".icon-preview"); old.replaceWith(icon(picker.value)); note(notice, "Hay cambios sin publicar."); }); row.appendChild(picker); }
  function renderBase() { baseList.replaceChildren(); base.forEach(([id, title]) => { const row = document.createElement("div"), name = document.createElement("strong"); row.className = "icon-row"; name.textContent = title; row.append(icon(icons[id] || defaults[id]), name); addChangeIcon(row, icons[id] || defaults[id], (value) => { icons[id] = value; }); baseList.appendChild(row); }); }
  function render() { renderBase(); list.replaceChildren(); if (!options.length) { const empty = document.createElement("p"); empty.className = "empty"; empty.textContent = "Aún no hay opciones adicionales."; list.appendChild(empty); return; } options.forEach((item, index) => { const row = document.createElement("article"), title = document.createElement("h3"), detail = document.createElement("p"), remove = document.createElement("button"); row.className = "saved-option"; title.textContent = item.title; detail.textContent = `${item.question} · ${item.choices.length} alternativas`; remove.type = "button"; remove.className = "remove-button"; remove.textContent = "Eliminar"; remove.addEventListener("click", () => { options.splice(index, 1); render(); note(notice, "Hay cambios sin publicar."); }); row.append(icon(item.icon || "sparkles"), title, detail); addChangeIcon(row, item.icon || "sparkles", (value) => { item.icon = value; }); row.appendChild(remove); list.appendChild(row); }); }
  async function api(url, method, body) { const response = await fetch(url, { method, credentials: "same-origin", headers: body ? { "Content-Type": "application/json" } : {}, body: body ? JSON.stringify(body) : undefined, cache: "no-store" }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "request_failed"); return data; }
  async function open() { const [data, kioskData] = await Promise.all([api("/api/admin/options", "GET"), api("/api/admin/kiosk", "GET")]); options = Array.isArray(data.options) ? data.options : []; icons = data.icons && typeof data.icons === "object" ? data.icons : {}; kiosk = kioskData.settings || kiosk; $("kiosk-width").value = kiosk.width; $("kiosk-height").value = kiosk.height; loginCard.hidden = true; adminCard.hidden = false; render(); }
  loginForm.addEventListener("submit", async (event) => { event.preventDefault(); note(loginNotice, ""); try { await api("/api/admin/login", "POST", { password: password.value }); password.value = ""; await open(); } catch (error) { note(loginNotice, error.message === "invalid_credentials" ? "No pudimos validar la credencial." : "El panel no está disponible. Verifica su configuración.", true); } });
  form.addEventListener("submit", (event) => { event.preventDefault(); const title = $("option-title").value.trim(), id = $("option-id").value.trim().toLowerCase(), description = $("option-description").value.trim(), question = $("option-question").value.trim(), choices = $("option-choices").value.split(/\r?\n/).map((value) => value.trim()).filter(Boolean); if (!/^[a-z0-9-]{2,40}$/.test(id) || !title || !description || !question || !choices.length || choices.length > 12 || options.some((item) => item.id === id)) return note(notice, "Revisa el identificador y las alternativas antes de agregar la opción.", true); if (options.length >= 10) return note(notice, "Solo se permiten diez opciones adicionales.", true); options.push({ id, title, description, question, choices, icon: newIcon.value }); form.reset(); newIcon.value = "sparkles"; render(); note(notice, "Opción agregada. Guarda los cambios para publicarla."); });
  save.addEventListener("click", async () => { save.disabled = true; note(notice, "Guardando cambios…"); try { const data = await api("/api/admin/options", "PUT", { options, icons }); options = data.options; icons = data.icons; render(); note(notice, "Cambios publicados en GAIA."); } catch { note(notice, "No pudimos publicar los cambios. Inicia sesión de nuevo e intenta otra vez.", true); } finally { save.disabled = false; } });
  $("reset-pin").addEventListener("click", async () => { const cedula = normalizeCedula($("pin-cedula").value); if (!cedula) return note($("pin-notice"), "Ingresa una cédula válida de 11 dígitos.", true); $("reset-pin").disabled = true; try { await api("/api/admin/pins", "POST", { cedula }); $("pin-cedula").value = ""; note($("pin-notice"), "PIN restablecido. La persona podrá crear uno nuevo al entrar."); } catch { note($("pin-notice"), "No pudimos restablecer el PIN. Inicia sesión de nuevo e intenta otra vez.", true); } finally { $("reset-pin").disabled = false; } });
  $("save-kiosk").addEventListener("click", async () => { const width = Number($("kiosk-width").value), height = Number($("kiosk-height").value); if (!Number.isInteger(width) || !Number.isInteger(height) || width < 640 || width > 3840 || height < 480 || height > 2160) return note($("kiosk-notice"), "Usa un ancho entre 640 y 3840, y un alto entre 480 y 2160 píxeles.", true); const button = $("save-kiosk"); button.disabled = true; note($("kiosk-notice"), "Guardando tamaño…"); try { const data = await api("/api/admin/kiosk", "PUT", { settings: { width, height } }); kiosk = data.settings; note($("kiosk-notice"), `Kiosco de Tecnología ajustado a ${kiosk.width} × ${kiosk.height}.`); } catch { note($("kiosk-notice"), "No pudimos guardar el tamaño. Inicia sesión de nuevo e intenta otra vez.", true); } finally { button.disabled = false; } });
  $("logout").addEventListener("click", async () => { try { await api("/api/admin/logout", "POST"); } catch {} options = []; icons = {}; adminCard.hidden = true; loginCard.hidden = false; password.focus(); });
  Object.entries(catalog).forEach(([id, label]) => { const item = document.createElement("option"); item.value = id; item.textContent = label; newIcon.appendChild(item); }); newIcon.value = "sparkles";
})();
